apiVersion: v1
kind: Service
metadata:
  name: rockstar-java-server-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: rockstar-java-server