apiVersion: v1
kind: Service
metadata:
  name: rockstar-dotnet-webmvc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: rockstar-dotnet-webmvc